schema_version: 1

context:
  python_min: "3.12"
  version: "0.8.1"

package:
  name: fixbikenet
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/fixbikenet/fixbikenet-${{ version }}.tar.gz
  sha256: 65be86ad222c68978eb810f781d77b220e702d9a27cd8bbd9e2f8fca42078d5b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77.0.3
    - pip
  run:
    - python >=${{ python_min }}
    - geopandas >=1
    - matplotlib-base
    - osmnx >=2
    - geojson
    - tqdm

tests:
  - python:
      imports:
        - fixbikenet
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: BikeNetKit Python package to detect gaps in developed bicycle networks
  license: AGPL-3.0-only
  license_file: LICENSE
  homepage: https://bikenetkit.org/
  documentation: https://docs.bikenetkit.org/FixBikeNet/
  repository: https://github.com/BikeNetKit/FixBikeNet

extra:
  recipe-maintainers:
    - mszell
